trigger:
- main

pr:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Building the application"
      displayName: 'Build'

- stage: Test
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Running tests"
      displayName: 'Run Tests'

- stage: Prod
  jobs:
  - deployment: DeployToProduction
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Deploying to Production"
            displayName: 'Deploy to Production'
